feat(env): increase max readers limit depending on number of workers
Kong/lua-resty-lmdb pull request #59
Opened 2024-11-06 08:26 UTC by Oyami-Srk

[KAG-5700](https://konghq.atlassian.net/browse/KAG-5700)

2024-11-12 09:19 UTC, dndx requested changes
Let's write a test with very large `worker_processes` to confirm the fix.

2024-11-13 06:28 UTC, Oyami-Srk commented
Test is added as `t/12-max-readers.t`

2024-11-21 12:48 UTC, dndx requested changes

2024-11-21 12:48 UTC, dndx commented on src/ngx_lua_resty_lmdb_module.c
> +    readers = (size_t)ccf->worker_processes;
```suggestion
    readers = (size_t) ccf->worker_processes;
```

2024-11-21 12:48 UTC, dndx commented on src/ngx_lua_resty_lmdb_module.c
> +              readers : NGX_LUA_RESTY_LMDB_DEFAULT_READERS;
```suggestion
              readers : NGX_LUA_RESTY_LMDB_DEFAULT_READERS;

```

2024-11-21 12:53 UTC, chronolaw commented on src/ngx_lua_resty_lmdb_module.c
> +    ngx_core_conf_t            *ccf;
style, should be:
```
  readers;
 *ccf;
```

2024-11-21 13:04 UTC, chronolaw commented on src/ngx_lua_resty_lmdb_module.c
> +    readers = readers > NGX_LUA_RESTY_LMDB_DEFAULT_READERS ?
`if ` may be easier to read?
```
if (readers < NGX_LUA_RESTY_LMDB_DEFAULT_READERS) {
  readers = NGX_LUA_RESTY_LMDB_DEFAULT_READERS
}
```

2024-11-22 01:51 UTC, Oyami-Srk commented on src/ngx_lua_resty_lmdb_module.c
> +    readers += NGX_LUA_RESTY_LMDB_MAX_READERS_REDUNDANCY;
done.

2024-11-22 01:52 UTC, Oyami-Srk commented on src/ngx_lua_resty_lmdb_module.c
> +    ngx_core_conf_t            *ccf;
done.

2024-11-22 01:52 UTC, Oyami-Srk commented on src/ngx_lua_resty_lmdb_module.c
> +    readers = (size_t)ccf->worker_processes;
done.

2024-11-22 02:14 UTC, chronolaw approved these changes

2024-11-22 02:59 UTC, dndx commented on src/ngx_lua_resty_lmdb_module.c
> +    readers = (size_t) ccf->worker_processes + NGX_LUA_RESTY_LMDB_MAX_READERS_REDUNDANCY;
```suggestion
    readers = (size_t) ccf->worker_processes + NGX_LUA_RESTY_LMDB_MAX_READERS_REDUNDANCY;

```

2024-11-22 03:33 UTC, dndx approved these changes

2024-11-22 03:34 UTC, merged