fix(module): allowing page size 1
Kong/lua-resty-lmdb pull request #60
Opened 2024-11-21 09:14 UTC by StarlightIbuki

2024-11-21 09:21 UTC, chobits approved these changes

2024-11-21 10:00 UTC, chobits commented on t/10-prefix.t
> +page_size must be at least 1
```suggestion
.*page_size must be at least 1
```

2024-11-21 10:01 UTC, chobits commented on t/10-prefix.t
> +            local ok, err= pcall(p.page, "test", "test", nil, 0)
```suggestion
            local ok, err = pcall(p.page, "test", "test", nil, 0)
```

2024-11-21 10:06 UTC, chobits approved these changes

2024-11-21 10:19 UTC, dndx requested changes
`README.md` API doc for `page` need to be updated.

2024-11-21 12:59 UTC, dndx commented on lib/resty/lmdb/prefix.lua
> +    if query_size < 2 then
Also `local math_max = math.max` as well.

2024-11-21 13:11 UTC, chobits approved these changes

2024-11-22 02:28 UTC, dndx requested changes

2024-11-22 02:28 UTC, dndx commented on README.md
> +If `page_size` is specified, up to `page_size` results will be returned.
```suggestion
If `page_size` is specified, up to `page_size` results will be returned.
`page_size` can not be less than `1`.
```

2024-11-22 02:29 UTC, dndx commented
@StarlightIbuki This PR needs to fix it's tests and rebase with the correct `TEST` number in the `.t` file.

2024-11-22 02:32 UTC, chronolaw approved these changes

2024-11-22 03:12 UTC, dndx approved these changes

2024-11-22 03:33 UTC, merged